//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step1StopMarketBUYPRICE {
            get {
                return ((decimal)(this["Step1StopMarketBUYPRICE"]));
            }
            set {
                this["Step1StopMarketBUYPRICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step1TakeProfitSELLPercent {
            get {
                return ((decimal)(this["Step1TakeProfitSELLPercent"]));
            }
            set {
                this["Step1TakeProfitSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step1StopMarketSELLPRICE {
            get {
                return ((decimal)(this["Step1StopMarketSELLPRICE"]));
            }
            set {
                this["Step1StopMarketSELLPRICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step1TakeProfitBUYPercent {
            get {
                return ((decimal)(this["Step1TakeProfitBUYPercent"]));
            }
            set {
                this["Step1TakeProfitBUYPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step2StopMarketSELLPercent {
            get {
                return ((decimal)(this["Step2StopMarketSELLPercent"]));
            }
            set {
                this["Step2StopMarketSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step2StopMarketBuyPercent {
            get {
                return ((decimal)(this["Step2StopMarketBuyPercent"]));
            }
            set {
                this["Step2StopMarketBuyPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step3TakeProfitBUYPercent {
            get {
                return ((decimal)(this["Step3TakeProfitBUYPercent"]));
            }
            set {
                this["Step3TakeProfitBUYPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step3StopMarketBUYPercent {
            get {
                return ((decimal)(this["Step3StopMarketBUYPercent"]));
            }
            set {
                this["Step3StopMarketBUYPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step3TakeProfitSELLPercent {
            get {
                return ((decimal)(this["Step3TakeProfitSELLPercent"]));
            }
            set {
                this["Step3TakeProfitSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step3StopMarketSELLPercent {
            get {
                return ((decimal)(this["Step3StopMarketSELLPercent"]));
            }
            set {
                this["Step3StopMarketSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step4TakeProfitSELLPercent {
            get {
                return ((decimal)(this["Step4TakeProfitSELLPercent"]));
            }
            set {
                this["Step4TakeProfitSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step4StopMarketSELLPercent {
            get {
                return ((decimal)(this["Step4StopMarketSELLPercent"]));
            }
            set {
                this["Step4StopMarketSELLPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step4TakeProfitBUYPercent {
            get {
                return ((decimal)(this["Step4TakeProfitBUYPercent"]));
            }
            set {
                this["Step4TakeProfitBUYPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Step4StopMarketBUYPercent {
            get {
                return ((decimal)(this["Step4StopMarketBUYPercent"]));
            }
            set {
                this["Step4StopMarketBUYPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Network {
            get {
                return ((decimal)(this["Network"]));
            }
            set {
                this["Network"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverloadRetry {
            get {
                return ((bool)(this["OverloadRetry"]));
            }
            set {
                this["OverloadRetry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverloadRetryAttempts {
            get {
                return ((int)(this["OverloadRetryAttempts"]));
            }
            set {
                this["OverloadRetryAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idOrder {
            get {
                return ((int)(this["idOrder"]));
            }
            set {
                this["idOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BOTstartQty {
            get {
                return ((int)(this["BOTstartQty"]));
            }
            set {
                this["BOTstartQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("apokaracha")]
        public string key {
            get {
                return ((string)(this["key"]));
            }
            set {
                this["key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goshko")]
        public string secret {
            get {
                return ((string)(this["secret"]));
            }
            set {
                this["secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.bitmex.com")]
        public string domain {
            get {
                return ((string)(this["domain"]));
            }
            set {
                this["domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wss://www.bitmex.com/realtime")]
        public string socketDomain {
            get {
                return ((string)(this["socketDomain"]));
            }
            set {
                this["socketDomain"] = value;
            }
        }
    }
}
